import song from "./askim.mp3"

export default [
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
    {
      title: "lofi hip hop radio 🎈 relax/study/sleep/yoga",
      singer: "bibobibo",
      time: "3:50",
      audioSrc:song,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOAYqzCfTE_C26Wxw65VlWrOJ-c7RCHpKFacmkBiK6HFOOQTrxerwAzRSG5iLkll-Erzw&usqp=CAU",
    },
  ];